import { Badge } from "./ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";

export function MapPreview() {
  const artifacts = [
    [".lumina/routes.json", "route tree"],
    [".lumina/render-manifest.json", "render modes"],
    [".lumina/map.json", "file edges"],
  ];

  const flow = [
    "Source routes are discovered from the app directory.",
    "Generated manifests record route, render, and map evidence.",
    "CLI inspection reads that evidence instead of guessing from prose.",
  ];

  return (
    <section className="section-shell map-preview-grid" aria-labelledby="map-preview-title">
      <div className="section-heading">
        <Badge variant="secondary">Lumina Map preview</Badge>
        <h2 id="map-preview-title">A route should explain its source, outputs, and risk surface.</h2>
        <p>
          The current map output connects routes to source files, layouts, render-mode evidence,
          and generated artifacts so inspect commands can explain why a route exists.
        </p>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Current generated evidence</CardTitle>
          <CardDescription>These files are regenerated by the existing Lumina commands.</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="map-artifact-list">
            {artifacts.map(([path, label]) => (
              <li key={path}>
                <span className="code-path">{path}</span>
                <Badge variant="outline">{label}</Badge>
              </li>
            ))}
          </ul>
          <div className="flow-board" aria-label="Map generation flow">
            {flow.map((step, index) => (
              <div className="flow-step" key={step}>
                <span className="flow-index">{index + 1}</span>
                <span>{step}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </section>
  );
}
